var menuList = [
    {
        name:'系统管理',
        second:[
            {
                name:'组织架构',
                third:[
                    {name:'经销商基本信息',url:'one'},
                    {name:'部门定义',url:'one'},
                    {name:'职务定义',url:'one'},
                    {name:'员工信息管理',url:'one'}
                ]
            },
            {
                name:'基础参数',
                third: [
                    {name:'基础参数设置',url:'one'},
                    {name:'积分规则查询',url:'one'}
                ]
            },
            {
                name:'预约维修',
                third:[
                    {name:'工时单价',url:'two'},
                    {name:'维修类型',url:'two'},
                    {name:'保险公司',url:'two'},
                    {name:'险种定义',url:'two'},
                    {name:'品牌车系车型',url:'two'},
                    {name:'维修项目类型',url:'two'}
                ]
            },
            {
                name:'用户安全',
                third:[
                    {name:'角色权限管理',url:'three'},
                    {name:'用户权限管理',url:'three'},
                    {name:'更改口令',url:'three'}
                ]
            },
            {
                name:'配件工具',
                third:[
                    {name:'工具类别',url:'three'},
                    {name:'计量单位',url:'three'},
                    {name:'业务往来类型',url:'three'},
                    {name:'配件类别',url:'three'}
                ]
            },
            {
                name:'结算收款',
                third:[
                    {name:'发票类型',url:'four'},
                    {name:'收款方式',url:'four'},
                    {name:'附加项目',url:'four'},
                    {name:'减免类型',url:'four'},
                    {name:'资金来源',url:'four'},
                    {name:'金融机构',url:'four'},
                    {name:'银行账户',url:'four'},
                    {name:'收费区分',url:'four'},
                    {name:'优惠',url:'four'}
                ]
            },
            {
                name:'初始化',
                third:[
                    {name:'在库车辆导入',url:'five'},
                    {name:'在途车辆导入',url:'five'},
                    {name:'车主车辆资料导入',url:'five'},
                    {name:'配件库存导入',url:'five'},
                    {name:'工具采购入库导入',url:'five'}
                ]
            },
            {
                name:'系统监控',
                third:[]
            }
        ]
    },
    {
        name:'客户管理',
        second:[
            {
                name:'潜客管理',
                third:[
                    {name:'展厅流量登记',url:'flowMark'},
                    {name:'展厅接待',url:'reception'},
                    {name:'客户信息',url:'customerMessage'}
                ]
            }
        ]
    },
    {
        name:'销售管理',
        second:[
            {name:'销售管理菜单'}
        ]
    },
    {
        name:'维修管理',
        second:[
            {name:'维修管理菜单'}
        ]
    },
    {
        name:'配件管理',
        second:[
            {name:'配件管理菜单'}
        ]
    },
    {
        name:'衍生管理',
        second:[
            {name:'衍生管理菜单'}
        ]
    },
    {
        name:'结算管理',
        second:[
            {name:'结算管理菜单'}
        ]
    },
    {
        name:'报表管理',
        second:[
            {name:'报表管理菜单'}
        ]
    },
    {
        name:'集团管理',
        second:[
            {name:'集团管理菜单'}
        ]
    },
    {
        name:'二手车',
        second:[
            {name:'二手车'}
        ]
    },
]

export default menuList
